/****** Script do comando SelectTopNRows de SSMS  ******/

--SAFRA = ANO-MESC

SELECT [SAFRA_CADASTRO], COUNT(SAFRA_CADASTRO) AS CONTAGEM
FROM (
	SELECT --TOP (1000) 
		   [IDCLIENTETITULARPESSOAFISICA]=RTRIM(LTRIM([IDCLIENTETITULARPESSOAFISICA]))
		  ,[DATACADASTRO]
		  ,[DATACADASTRO_TRATADO]=CONVERT(DATE,[DATACADASTRO],101)
		  ,[ANO_DATACADASTRO]=YEAR(CONVERT(DATE,[DATACADASTRO],101))
		  ,[MES_DATACADASTRO]=MONTH(CONVERT(DATE,[DATACADASTRO],101))
		  ,[MES_DATACADASTRO_TRATADO] = CASE WHEN LEN( CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))) = 1 THEN '0'+ CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))
											 ELSE CONVERT (CHAR, MONTH (CONVERT(DATE,[DATACADASTRO],101)))
										END
		  ,[SAFRA_CADASTRO]=LTRIM(RTRIM(CONVERT(CHAR,YEAR(CONVERT(DATE,[DATACADASTRO],101)))))+CONVERT(CHAR,CASE WHEN LEN( CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))) = 1 THEN '0'+''+CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))
											 ELSE CONVERT (CHAR, MONTH (CONVERT(DATE,[DATACADASTRO],101)))
										END)
		  ,[SAFRA_CADASTRO_TRATADO]=CONVERT(INT,LTRIM(RTRIM(CONVERT(CHAR,YEAR(CONVERT(DATE,[DATACADASTRO],101)))))+CONVERT(CHAR,CASE WHEN LEN( CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))) = 1 THEN '0'+''+CONVERT(CHAR, MONTH(CONVERT(DATE,[DATACADASTRO],101)))
											 ELSE CONVERT (CHAR, MONTH (CONVERT(DATE,[DATACADASTRO],101)))
										END))
		  ,[TELEFONE_RESIDENCIAL]
		  ,[TELEFONE_CELULAR]
		  ,[TELEFONE_COMERCIAL]
		  ,[ESCOLARIDADE]
		  ,[DATANASCIMENTO]
		  ,[CEP]
		  ,[ESTADO]
		  ,[RENDA]
		  ,[PROFISSAO]
		  ,[ESTADOCIVIL]
		  ,[TIPOMORADIA]
		  ,[LIMITE TOTAL]
		  ,[LIMITE DISPONÍVEL]
	  FROM [RISK_SCORE].[dbo].[base_cadastro]
  )A

GROUP BY SAFRA_CADASTRO
ORDER BY SAFRA_CADASTRO